services:
  backend:
    build:
      context: "D:/movies-webapp"
    ports:
      - "8080:8080"
    volumes:
      - D:/movies-webapp/uploads:/app/uploads
      - D:/movies-webapp/video:/app/video
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/movies_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: "D:/movies-UI"
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: movies_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
